AbstractObserver.cpp
ActiveDispatcher.cpp
ArchiveStrategy.cpp
Ascii.cpp
ASCIIEncoding.cpp
AsyncChannel.cpp
AtomicCounter.cpp
Base32Decoder.cpp
Base32Encoder.cpp
Base64Decoder.cpp
Base64Encoder.cpp
BinaryReader.cpp
BinaryWriter.cpp
BLAKE2Engine.cpp
Bugcheck.cpp
ByteOrder.cpp
Channel.cpp
Checksum.cpp
Clock.cpp
compress.c
Condition.cpp
Configurable.cpp
ConsoleChannel.cpp
CountingStream.cpp
DateTime.cpp
DateTimeFormat.cpp
DateTimeFormatter.cpp
DateTimeParser.cpp
Debugger.cpp
DeflatingStream.cpp
DigestEngine.cpp
DigestStream.cpp
DirectoryIterator.cpp
DirectoryIteratorStrategy.cpp
DirectoryWatcher.cpp
Environment.cpp
Error.cpp
ErrorHandler.cpp
Event.cpp
EventArgs.cpp
EventChannel.cpp
EventLogChannel.cpp
Exception.cpp
FIFOBufferStream.cpp
File.cpp
FileChannel.cpp
FileStream.cpp
FileStreamFactory.cpp
Format.cpp
Formatter.cpp
FormattingChannel.cpp
FPEnvironment.cpp
Glob.cpp
Hash.cpp
HashStatistic.cpp
HexBinaryDecoder.cpp
HexBinaryEncoder.cpp
InflatingStream.cpp
JSONString.cpp
Latin1Encoding.cpp
Latin2Encoding.cpp
Latin9Encoding.cpp
LineEndingConverter.cpp
LocalDateTime.cpp
LogFile.cpp
LogFile_STD.cpp
Logger.cpp
LoggingFactory.cpp
LoggingRegistry.cpp
LogStream.cpp
Manifest.cpp
MD4Engine.cpp
MD5Engine.cpp
MemoryPool.cpp
MemoryStream.cpp
Message.cpp
Mutex.cpp
NamedEvent.cpp
NamedMutex.cpp
NestedDiagnosticContext.cpp
Notification.cpp
NotificationCenter.cpp
NotificationQueue.cpp
NullChannel.cpp
NullStream.cpp
NumberFormatter.cpp
NumberParser.cpp
NumericString.cpp
Path.cpp
PatternFormatter.cpp
Pipe.cpp
PipeImpl.cpp
PipeStream.cpp
pocomsg.mc
PriorityNotificationQueue.cpp
Process.cpp
PurgeStrategy.cpp
Random.cpp
RandomStream.cpp
RefCountedObject.cpp
RegularExpression.cpp
RotateStrategy.cpp
Runnable.cpp
RWLock.cpp
Semaphore.cpp
SHA1Engine.cpp
SHA2Engine.cpp
SHA3Engine.cpp
SharedLibrary.cpp
SharedMemory.cpp
SignalHandler.cpp
SimpleFileChannel.cpp
SortedDirectoryIterator.cpp
SplitterChannel.cpp
Stopwatch.cpp
StreamChannel.cpp
StreamConverter.cpp
StreamCopier.cpp
StreamTokenizer.cpp
String.cpp
StringTokenizer.cpp
SynchronizedObject.cpp
Task.cpp
TaskManager.cpp
TaskNotification.cpp
TeeStream.cpp
TemporaryFile.cpp
TextBufferIterator.cpp
TextConverter.cpp
TextEncoding.cpp
TextIterator.cpp
Thread.cpp
ThreadLocal.cpp
ThreadPool.cpp
ThreadTarget.cpp
TimedNotificationQueue.cpp
Timer.cpp
Timespan.cpp
Timestamp.cpp
Timezone.cpp
Token.cpp
Unicode.cpp
UnicodeConverter.cpp
URI.cpp
URIStreamFactory.cpp
URIStreamOpener.cpp
UTF16Encoding.cpp
UTF32Encoding.cpp
UTF8Encoding.cpp
UTF8String.cpp
UUID.cpp
UUIDGenerator.cpp
Var.cpp
VarHolder.cpp
VarIterator.cpp
Void.cpp
Windows1250Encoding.cpp
Windows1251Encoding.cpp
Windows1252Encoding.cpp

Foundation_SOURCES_C99
FPEnvironment_C99.cpp

Foundation_SOURCES_POSIX 
Mutex_POSIX.cpp
Event_POSIX.cpp
FileStream_POSIX.cpp
PipeImpl_POSIX.cpp
SharedMemory_POSIX.cpp
RWLock_POSIX.cpp
Semaphore_POSIX.cpp
Thread_POSIX.cpp

Foundation_SOURCES_UNIX
NamedMutex_UNIX.cpp
NamedEvent_UNIX.cpp
DirectoryIterator_UNIX.cpp
Environment_UNIX.cpp
File_UNIX.cpp
Path_UNIX.cpp
Process_UNIX.cpp
SharedLibrary_UNIX.cpp
Timezone_UNIX.cpp
SyslogChannel.cpp

Foundation_SOURCES_Android
NamedMutex_Android.cpp
NamedEvent_Android.cpp
AndroidLogChannel.cpp
RWLock_Android.cpp

Foundation_Win32
Mutex_WIN32.cpp
NamedMutex_WIN32.cpp
NamedMutex_WIN32U.cpp
NamedEvent_WIN32.cpp
NamedEvent_WIN32U.cpp
DirectoryIterator_WIN32.cpp
DirectoryIterator_WIN32U.cpp
Event_WIN32.cpp
Environment_WIN32.cpp
Environment_WIN32U.cpp
File_WIN32.cpp
File_WIN32U.cpp
FileStream_WIN32.cpp
FPEnvironment_WIN32.cpp
LogFile_WIN32.cpp
LogFile_WIN32U.cpp
Path_WIN32.cpp
Path_WIN32U.cpp
PipeImpl_WIN32.cpp
Process_WIN32.cpp
Process_WIN32U.cpp
RWLock_WIN32.cpp
RWLock_WINCE.cpp
Semaphore_WIN32.cpp
SharedLibrary_WIN32.cpp
SharedLibrary_WIN32U.cpp
SharedMemory_WIN32.cpp
Thread_WIN32.cpp
Timezone_WIN32.cpp
WindowsConsoleChannel.cpp

Foundation_SOURCES_pcre
pcre_byte_order.c
pcre_chartables.c
pcre_compile.c
pcre_config.c
pcre_dfa_exec.c
pcre_exec.c
pcre_fullinfo.c
pcre_get.c
pcre_globals.c
pcre_jit_compile.c
pcre_maketables.c
pcre_newline.c
pcre_ord2utf8.c
pcre_refcount.c
pcre_string_utils.c
pcre_study.c
pcre_tables.c
pcre_ucd.c
pcre_valid_utf8.c
pcre_version.c
pcre_xclass.c

Foundation_SOURCES_pcre
pcre.h
pcre_config.h
pcre_internal.h

Foundation_SOURCES_zlib
adler32.c
compress.c
crc32.c
deflate.c
infback.c
inffast.c
inflate.c
inftrees.c
trees.c
zutil.c

